import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging
from sqlalchemy.orm import Session
from db.models import Admin

logger = logging.getLogger(__name__)

def send_alert(source_name: str, new_items: list, db: Session):
    # Fetch admin emails
    admins = db.query(Admin).all()
    if not admins:
        logger.info("No admin alert receivers registered in database. Skipping email alert dispatch.")
        return

    recipient_emails = [admin.email for admin in admins]
    from_email = os.getenv("ADMIN_FROM_EMAIL", "alerts@yourdomain.com")
    mail_password = os.getenv("MAIL_PASSWORD", "").strip()

    # Construct clean, premium HTML body in green and gold styles matching aggregator theme
    html_content = f"""
    <div style="font-family: Arial, sans-serif; background-color: #f7f9f8; padding: 20px; border-radius: 8px; border: 1px solid #e1e8e5; max-width: 600px; margin: 0 auto;">
        <div style="background-color: #0b2e1c; padding: 15px; border-radius: 6px 6px 0 0; border-bottom: 3px solid #d4af37; text-align: center; color: #ffffff;">
            <span style="font-size: 24px; vertical-align: middle;">🇵🇰</span>
            <h2 style="margin: 0; display: inline-block; font-size: 20px; font-weight: bold; letter-spacing: 0.05em; padding-left: 8px;">Pakistan Law Aggregator</h2>
        </div>
        <div style="padding: 24px; background-color: #ffffff; color: #333333;">
            <p style="font-size: 16px; line-height: 1.5;">New legislative updates have been scraped and verified from <strong>{source_name}</strong>:</p>
            <ul style="padding-left: 20px; font-size: 15px; line-height: 1.6; color: #1a4f32;">
    """
    
    for item in new_items:
        html_content += f'<li style="margin-bottom: 8px; font-weight: 500;">{item}</li>'
        
    html_content += f"""
            </ul>
            <p style="font-size: 14px; margin-top: 24px; color: #666666;">Log in to the administrator control panel to view full metrics and download PDFs.</p>
        </div>
        <div style="background-color: #f1f4f2; padding: 12px; border-radius: 0 0 6px 6px; font-size: 11px; color: #888888; text-align: center;">
            This is an automated alert generated by Pakistan Law Aggregator Engine. Do not reply.
        </div>
    </div>
    """

    subject = f"Law Alert: New updates from {source_name}"

    # SMTP Dispatch Path
    if from_email and mail_password:
        try:
            logger.info(f"Dispatching email via SMTP to receivers: {recipient_emails}")
            
            # Setup MIME message
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = from_email
            msg["To"] = ", ".join(recipient_emails)
            
            # Attach HTML version
            part = MIMEText(html_content, "html")
            msg.attach(part)
            
            # Connect to Gmail SMTP server
            smtp_host = "smtp.gmail.com"
            smtp_port = 587
            
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=15)
            server.starttls()
            server.login(from_email, mail_password)
            server.sendmail(from_email, recipient_emails, msg.as_string())
            server.quit()
            
            logger.info("SMTP dispatch succeeded.")
            return
        except Exception as smtp_err:
            logger.error(f"Failed to dispatch email via SMTP: {smtp_err}")
            logger.info("Attempting fallback notification mechanisms.")

    # Resend API Dispatch Path
    api_key = os.getenv("RESEND_API_KEY")
    if api_key:
        import resend
        try:
            resend.api_key = api_key
            logger.info(f"Dispatching email via Resend to receivers: {recipient_emails}")
            resend.Emails.send({
                "from": from_email,
                "to": recipient_emails,
                "subject": subject,
                "html": html_content
            })
            logger.info("Resend dispatch succeeded.")
            return
        except Exception as resend_err:
            logger.error(f"Failed to dispatch email via Resend API: {resend_err}")

    # Fallback/Simulation Log Path
    logger.info("=" * 60)
    logger.info("[SIMULATION MODE] - No successful email dispatch. Log output below:")
    logger.info(f"From: {from_email}")
    logger.info(f"To: {recipient_emails}")
    logger.info(f"Subject: {subject}")
    logger.info("-" * 60)
    logger.info(html_content)
    logger.info("=" * 60)
